# Generated by Django 2.2 on 2019-04-03 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('p_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(default=0)),
                ('date_crated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment', models.CharField(max_length=100)),
                ('date_assigned', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app.Person')),
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('care_date_from', models.DateField()),
                ('care_date_to', models.DateField()),
                ('medical_state', models.CharField(choices=[('1', 'Deadly'), ('2', 'Emergency'), ('3', 'Checkup')], max_length=100)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Room')),
            ],
            bases=('app.person',),
        ),
        migrations.CreateModel(
            name='SickHistory',
            fields=[
                ('sick_hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('cause', models.TextField()),
                ('date_sickness', models.DateField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_history', to='app.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedHistory',
            fields=[
                ('medicament_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('dose', models.FloatField(default=0)),
                ('receipt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Receipt')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicament_history', to='app.Patient')),
            ],
        ),
    ]
