# Generated by Django 2.1.7 on 2019-03-29 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='care_date',
            new_name='care_date_from',
        ),
        migrations.AddField(
            model_name='patient',
            name='care_date_to',
            field=models.DateField(default=datetime.date(2019, 3, 29)),
            preserve_default=False,
        ),
    ]
