# Generated by Django 2.2 on 2019-04-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medhistory',
            old_name='receipt_id',
            new_name='receipt',
        ),
        migrations.AddField(
            model_name='receipt',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='app.Patient'),
        ),
    ]
