# Generated by Django 2.1.7 on 2019-03-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190329_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sick_hist_id',
        ),
        migrations.AddField(
            model_name='person',
            name='sick_hist_id',
            field=models.ManyToManyField(to='app.SickHistory'),
        ),
    ]
