# Generated by Django 2.1.7 on 2019-03-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190329_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='sick_hist_id',
            new_name='sick_hist',
        ),
    ]
