# Generated by Django 2.2 on 2019-04-04 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190404_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medhistory',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='med_history_receipts', to='app.Receipt'),
        ),
    ]
