# Generated by Django 2.1.7 on 2019-03-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190329_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sick_hist',
        ),
        migrations.AddField(
            model_name='person',
            name='sick_hist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.SickHistory'),
        ),
    ]
