# Generated by Django 2.1.7 on 2019-03-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190329_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sick_hist',
        ),
        migrations.AddField(
            model_name='sickhistory',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Person'),
        ),
    ]
