# Generated by Django 2.1.7 on 2019-03-29 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190329_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sickhistory',
            name='person',
        ),
        migrations.AddField(
            model_name='sickhistory',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Patient'),
        ),
    ]
