# Generated by Django 2.1.7 on 2019-03-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190329_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sickhistory',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_history', to='app.Patient'),
        ),
    ]
