# Generated by Django 2.1.7 on 2019-03-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190329_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='room_id',
        ),
        migrations.AddField(
            model_name='room',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Patient'),
        ),
        migrations.AddField(
            model_name='room',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Receipt'),
        ),
    ]
