# Generated by Django 2.1.7 on 2019-03-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190330_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='receipt',
        ),
    ]
