# Generated by Django 2.1.7 on 2019-03-30 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_room_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_room', to='app.Patient'),
        ),
    ]
