# Generated by Django 2.1.7 on 2019-03-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190330_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='medhistory',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicament_history', to='app.Patient'),
        ),
    ]
