# Generated by Django 2.1.7 on 2019-03-31 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190331_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Room'),
        ),
    ]
